"""Tool gateway contracts and provider adapters."""

from packages.tools.amap import (
    AmapAdapter,
    AmapProviderError,
    GeocodeCandidate,
    GeocodeInput,
    GeocodeOutput,
    PlaceSearchInput,
    PlaceSearchOutput,
)
from packages.tools.http_provider import (
    CircuitOpenError,
    HttpProviderPolicy,
    MemoryAuditSink,
    ProviderCallAudit,
    ProviderHttpError,
    ProviderResponseTooLargeError,
    ProviderUnavailableError,
    ResilientHttpProvider,
)
from packages.tools.mcp_adapter import (
    MCP_PROTOCOL_VERSION,
    McpAdapter,
    McpAdapterError,
    McpServerConfig,
    McpToolOutput,
    StdioMcpTransport,
    StreamableHttpMcpTransport,
)
from packages.tools.registry import build_default_registry, default_tool_definitions
from packages.tools.routes import (
    AmapRouteAdapter,
    MapPolyline,
    RouteComputeInput,
    RouteComputeOutput,
    RouteEndpoint,
    RouteMatrixInput,
    RouteMatrixOutput,
    to_gcj02,
)
from packages.tools.travel_stubs import (
    FixtureTravelProviders,
    FlightProvider,
    FlightSearchInput,
    FlightSearchOutput,
    LodgingProvider,
    LodgingSearchInput,
    LodgingSearchOutput,
    RailOfficialLinkInput,
    RailOfficialLinkOutput,
)
from packages.tools.weather import (
    OpenMeteoAdapter,
    WeatherForecastInput,
    WeatherForecastOutput,
)

__all__ = [
    "AmapAdapter",
    "AmapProviderError",
    "AmapRouteAdapter",
    "CircuitOpenError",
    "FixtureTravelProviders",
    "FlightProvider",
    "FlightSearchInput",
    "FlightSearchOutput",
    "GeocodeCandidate",
    "GeocodeInput",
    "GeocodeOutput",
    "HttpProviderPolicy",
    "MemoryAuditSink",
    "MCP_PROTOCOL_VERSION",
    "McpAdapter",
    "McpAdapterError",
    "McpServerConfig",
    "McpToolOutput",
    "MapPolyline",
    "LodgingProvider",
    "LodgingSearchInput",
    "LodgingSearchOutput",
    "OpenMeteoAdapter",
    "PlaceSearchInput",
    "PlaceSearchOutput",
    "ProviderCallAudit",
    "ProviderHttpError",
    "ProviderResponseTooLargeError",
    "ProviderUnavailableError",
    "RailOfficialLinkInput",
    "RailOfficialLinkOutput",
    "ResilientHttpProvider",
    "RouteComputeInput",
    "RouteComputeOutput",
    "RouteEndpoint",
    "RouteMatrixInput",
    "RouteMatrixOutput",
    "StdioMcpTransport",
    "StreamableHttpMcpTransport",
    "WeatherForecastInput",
    "WeatherForecastOutput",
    "build_default_registry",
    "default_tool_definitions",
    "to_gcj02",
]
